# Generated by Django 3.0.4 on 2020-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='userupvoted',
            field=models.ManyToManyField(to='empo_news.Contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='hidden_contributions', to='empo_news.Contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoted_contributions', to='empo_news.Contribution'),
        ),
    ]
