# Generated by Django 3.0.4 on 2020-04-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=1)),
                ('publication_date', models.DateTimeField(verbose_name='publication date')),
                ('text', models.CharField(max_length=2000)),
                ('contribution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empo_news.Contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empo_news.User')),
            ],
        ),
    ]
