# Generated by Django 3.0.4 on 2020-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
