# Generated by Django 3.0.4 on 2020-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0002_auto_20200326_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='username',
            new_name='user',
        ),
    ]
