# Generated by Django 3.0.4 on 2020-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0003_auto_20200430_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
