# Generated by Django 3.0.4 on 2020-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0004_contribution_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_publications',
            field=models.ManyToManyField(to='empo_news.Contribution'),
        ),
    ]
