# Generated by Django 3.0.4 on 2020-04-30 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empo_news', '0004_auto_20200430_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='user_id_hidden',
            field=models.ManyToManyField(blank=True, related_name='hide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='hidden',
        ),
        migrations.AddField(
            model_name='contribution',
            name='hidden',
            field=models.IntegerField(default=0),
        ),
    ]
