# Generated by Django 3.0.4 on 2020-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0005_auto_20200326_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_publications',
        ),
        migrations.AddField(
            model_name='user',
            name='hidden',
            field=models.ManyToManyField(default=None, related_name='hidden_contributions', to='empo_news.Contribution'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted',
            field=models.ManyToManyField(default=None, related_name='upvoted_contributions', to='empo_news.Contribution'),
        ),
    ]
