# Generated by Django 3.0.4 on 2020-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0007_auto_20200502_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfields',
            name='api_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
