# Generated by Django 3.0.4 on 2020-05-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0008_auto_20200502_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='likes',
        ),
    ]
