# Generated by Django 3.0.4 on 2020-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0009_remove_contribution_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='publication_time',
            field=models.DateTimeField(verbose_name='publication time'),
        ),
    ]
