# Generated by Django 3.0.4 on 2020-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empo_news', '0010_auto_20200508_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='url_domain',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
