openapi: 3.0.0
info:
  version: 1.0
  title: Empo News
  description: 'This is the Open API documentation for the REST API of **Empo News** deployed at '
  + '<https://empo-news.herokuapp.com/>. <br>All operations are executable. Only one operation requires authentication: `deleteTweet`.'' 
  + ' In this case, you must **Authorize** your request by providing the api_key vaule you got when you created the tweet.'
servers:
  - url: 'https://empo-news.herokuapp.com'
paths:
  /contributions:
    get:
      summary: 'Retrieves all the contributions'
      operationId: listContribution
      tags:
        - contributions
      responses:
        '200':
          description: List of all contributions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributionsList'
        default:
          description: 'Error: Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
    schemas:
        Contribution:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    
        ContributionsList:
            type: array
            items:
                type: object
                properties:
                    contribution:
                        $ref: '#/components/schemas/Contribution'
