openapi: 3.0.0
info:
  version: 1.0
  title: Empo News
  description: 'This is the Open API documentation for the REST API of **Empo News** deployed at <https://empo-news.herokuapp.com/>. <br>All operations are executable. Only one operation requires authentication: `deleteTweet`. In this case, you must **Authorize** your request by providing the api_key vaule you got when you created the tweet.'
servers:
  - url: 'https://empo-news.herokuapp.com'
paths:
  /contributions:
    get:
      summary: 'Retrieves all the contributions'
      operationId: listContribution
      tags:
        - contributions
      responses:
        '200':
          description: List of all contributions
          content:
            application/json:
                type: array
                items:
                    $ref: '#/components/schemas/Contribution'
        default:
          description: 'Error: Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 1
                username:
                    type: string
                    maxLenght: 150
                    example: 'John'
                first_name:
                    type: string
                    maxLenght: 30
                    example: 'Doe'
                last_name:
                    type: string
                    maxLenght: 150
                    example: 'García'
                password:
                    type: string
                    format: password
                    minLenght: 8
                    maxLenght: 128
                    example: 'asndqw23qDS'
                email:
                    type: string
                    format: email
                    maxLenght: 254
                    example: 'john.doe@mail.com'
                date_joined:
                    type: string
                    format: date-time
                    example: '2020-04-16 22:41:09.025719'
        Contribution:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 1
                title:
                    type: string
                    minLenght: 4
                    maxLenght: 2000
                    example: 'This is my first contribution'
                points:
                    type: integer
                    format: int32
                    default: 1
                    example: 3
                publication_time:
                    type: string
                    format: date-time
                    example: '2020-04-16 22:18:21.208736'
                url:
                    type: string
                    nullable: true
                    format: url
                    maxLength: 500
                    example: 'https://google.com'
                text:
                    type: string
                    nullable: true
                    maxLength: 500
                    example: "Hello Wordl!"
                comments:
                    type: integer
                    format: int32
                    default: 0
                    example: 3
                user_id:
                    type: integer
                    format: int64
                    example: 2
        Error:
            type: object
              properties:
                status:
                  type: integer
                  enum: [400, 401, 403, 404, 409]
                error: 
                  type: string
                  enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict"]
                message: 
                  type: string
                examples:
                    error400:
                      value:
                        status: 400
                        error: "Bad Request"
                        message: "Content is too long (maximum is 280 characters)"
                    error401:
                      value:
                        status: 401
                        error: "Unauthorized"
                        message: "You provided no api key (X-API-KEY Header)"
                    error403:
                      value:
                        status: 403
                        error: "Forbidden"
                        message: "Your api key (X-API-KEY Header) is not valid"
                    error404:
                      value:
                        status: 404
                        error: "Not Found"
                        message: "No Tweet with that ID"
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            name: X-API-KEY #Custom headers in rails apps must have the X- prefix
            in: header